### PR TITLE
Add hook to test if configure should be run

### PR DESCRIPTION
**Pull request by cdosborn**
I also fixed some of the docs on symlinking the hooks.

### CODE REVIEW

**Comment by steve-gregory** [comment]
Pinging @amercer1 so he can add `git-hook injection` as a 'feature' for Clank.. (Once this is merged)

**Comment by cdosborn** [comment]
and its in 🌻 `bash` 🌷

**Comment by lenards** [comment]
I looked this over, I give it 👍

**Comment by lenards** [comment]
Is there anything holding this up?

**Pull request merged**
