### PR TITLE
correction event created for allocation source

### PR DESCRIPTION
**Pull request by amit4111989**

### CODE REVIEW

**Comment by steve-gregory** [comment]
@amit4111989 I pointed this branch to R-R can you confirm it looks as expected, then ill go ahead and :shipit:

**Comment by amit4111989** [comment]
I am including @julianpistorius here because he has the latest version of the code with exception handling for API calls

**Comment by julianpistorius** [comment]
Don't merge this just yet.  I have to check a few things.

**Comment by steve-gregory** [comment]
@julianpistorius when you are reviewing, please move the target branch to `solitary-snipe` or `master` as appropriate. `ravenous-raven` is in the 📖 now..

**Comment by steve-gregory** [comment]
@julianpistorius @amit4111989 before we merge this we may want to re-target from `ravenous-raven` to `solitary-snipe`

**Comment by amit4111989** [comment]
I think we may not need to merge this right now. @julianpistorius 's local repo has the more advanced version of the correction script anyway

https://github.com/julianpistorius/atmosphere/blob/corrections/scripts/rectify_allocations.py

**Pull request closed without merging**
