### PR TITLE
Revert "Update secrets template"

### PR DESCRIPTION
**Pull request by cdosborn**
This reverts commit 3b3bdef1e7a32bb27f98023deecd74508e6746eb. This commit should not have been merged in.

### CODE REVIEW

**Comment by lenards** [comment]
I believe this relates to commits and actions taken in PR #168.

**Comment by lenards** [comment]
I think this is good-to-go with the changes in `rtwo`/etc complete. 

:shipit:

**Comment by lenards** [comment]
@steve-gregory - I think this is ready to be merged.

**Comment by steve-gregory** [comment]
:shipit:

**Pull request merged**
