### PR TITLE
Dd hotfix

### PR DESCRIPTION
**Pull request by steve-gregory**
These changes to be applied ASAP

### CODE REVIEW

**Comment by amercer1** [comment]
+1 Now that you have time on the first of the months, watch Game Of Thrones!

**Comment by erbriones** [comment]
The commit a1353aec seems to be unrelated to the hotfix and looks like it needs more work (provider hardcoded). This commit should be pulled out from this pull request.

**Comment by steve-gregory** [comment]
@erbriones Both commits are required for DD to be fixed, Unless you see some problem with the commit, it will stay in the pull request and should be evaluated as such.

-Steve

**Comment by erbriones** [comment]
@steve-gregory The commit for the celery tasks is a feature/improvement. While the other commits relate directly to fixing the bug in sending emails. I see these as unrelated requests.

**Comment by steve-gregory** [comment]
After reviewing with @erbriones, a 'new improvement' will be added to JIRA for extending functionality to the celery task to be used in a less-iplant-exclusive manner.

**Pull request merged**
